server:
  port: 8080
mysql:
  datasource:
    test1:
      url: jdbc:mysql://127.0.0.1:3306/stu_myself?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 1973
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60

    test2:
      url: jdbc:mysql://127.0.0.1:3306/stu_myself?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: 1973
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60


